// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ 
  path: path.resolve(import.meta.dirname, "../../.env") 
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Not env(): it throws when unset, but `prisma generate` must work without a database (e.g. at build time)
    url: process.env.DATABASE_URL,
  },
});
